train: ../train/images
val: ../valid/images
test: ../test/images

nc: 3
names: ['Mate', 'Neutral', 'Prey']

roboflow:
  workspace: resistor-classification-scanner
  project: final_blue-bwnea
  version: 6
  license: CC BY 4.0
  url: https://universe.roboflow.com/resistor-classification-scanner/final_blue-bwnea/dataset/6